name: emergent_llm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter

  - openai
  - anthropic
  - transformers

  - pytest
  - tqdm
  - pyyaml
  - python-dotenv

  # dev packages
  - autoflake
  - epc
  - isort
  - pandas-stubs
  - ptvsd>=4.2
  - pylsp-mypy
  - python-lsp-server  # though included by pylsp-mypy

  - pip:
    - -e .  # Install this package in development mode

    # dev packages
    - importmagic
