[tool.mypy]
mypy_path = "src"
namespace_packages = true
explicit_package_bases = true

[tool.isort]
profile = "black"
src_paths = ["src"]
skip_gitignore = true

[tool.pylint.format]
max-line-length = 100

[tool.yapf]
based_on_style = "google"