"""
Generated LLM strategies for social dilemma games.

This file contains strategy classes generated by LLMs for game theory experiments.
Each strategy is a callable class that implements a specific approach to the game.

Generated with:
- Provider: Anthropic
- Model: claude-fable-5
- Effort: low
- Game: common_pool
"""

from dataclasses import dataclass
from enum import Enum
import math
import numpy as np
from numpy.typing import NDArray
import random

from emergent_llm.players import BaseStrategy
from emergent_llm.games import PublicGoodsDescription, CollectiveRiskDescription, CommonPoolDescription
from emergent_llm.common import Action, C, D, PlayerHistory




class Strategy_COLLECTIVE_1(BaseStrategy):
    """
    Sustainable Trigger with Proportional Forgiveness.
    Cooperates by default; short capped punishment against defecting
    populations; always cooperates when stock is endangered.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.avg_coop = 1.0
        self.consec_D = 0
        self.rounds_seen = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = max(n - 1, 1)
        while self.rounds_seen < t:
            cf = history.opponent_cooperators[self.rounds_seen] / opp
            self.avg_coop = 0.3 * self.avg_coop + 0.7 * cf
            self.rounds_seen += 1
        if t == 0:
            return Action.C
        last_coop_frac = history.opponent_cooperators[-1] / opp
        health = current_stock / cap if cap > 0 else 0.0
        if t == r - 1:
            return Action.C if self.avg_coop >= 0.5 else Action.D
        if health < 0.25:
            self.consec_D = 0
            return Action.C
        if self.avg_coop >= 0.6 or last_coop_frac >= 0.75 or (self.consec_D >= 2 and health >= 0.6):
            self.consec_D = 0
            return Action.C
        self.consec_D += 1
        return Action.D

class Strategy_COLLECTIVE_2(BaseStrategy):
    """
    Sustainable Trigger with Proportional Forgiveness.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.majority_defect_count = 0
        self.grim = False
        self.grim_defect_mode = True

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t == 0:
            return Action.C
        opp = n - 1
        d = opp - int(history.opponent_cooperators[-1])
        if opp > 0 and d >= opp / 2:
            self.majority_defect_count += 1
        if self.majority_defect_count > max(3, r / 4):
            self.grim = True
        if t == r - 1:
            return Action.D
        if t == r - 2:
            return Action.C if d == 0 and current_stock >= 0.5 * cap else Action.D
        if self.grim:
            if current_stock < 0.2 * cap:
                self.grim_defect_mode = False
                return Action.C
            if not self.grim_defect_mode:
                if current_stock >= 0.6 * cap:
                    self.grim_defect_mode = True
                    return Action.D
                return Action.C
            return Action.D
        if current_stock < 0.2 * cap:
            return Action.C
        if d == 0:
            return Action.C
        if t >= 2:
            d_prev = opp - int(history.opponent_cooperators[-2])
            if d < d_prev:
                return Action.C
        if opp > 0 and random.random() < d / opp:
            return Action.D
        return Action.C

class Strategy_COLLECTIVE_3(BaseStrategy):
    """
    Sustainable Trigger with Generous Recovery:
    tolerant tit-for-tat on aggregate defections, one-round punishment,
    stock-critical conservation, endgame defection.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punishing_flag = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        if t == r - 1:
            return Action.D
        d_prev = n - 1 - int(history.opponent_cooperators[-1])
        if current_stock < 0.2 * cap:
            return Action.C
        if self.punishing_flag:
            self.punishing_flag = False
            return Action.D
        if t == r - 2:
            return Action.D if d_prev >= n - 1 else Action.C
        if d_prev == 0:
            return Action.C
        if d_prev <= math.ceil((n - 1) / 3):
            return Action.C if random.random() < 0.8 else Action.D
        self.punishing_flag = True
        return Action.D

class Strategy_COLLECTIVE_4(BaseStrategy):
    """Sustainable Trigger with Proportional Forgiveness."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.avg_coop = 1.0
        self.probe_counter = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        if t == 0:
            return Action.C
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        denom = max(n - 1, 1)
        coop_frac = history.opponent_cooperators[-1] / denom
        self.avg_coop = 0.6 * self.avg_coop + 0.4 * coop_frac
        if t == r - 1:
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t >= r - 2 and self.avg_coop < 0.5:
            return Action.D
        if self.avg_coop >= 0.6:
            return Action.C
        if self.avg_coop >= 0.3:
            if current_stock >= 0.5 * cap:
                return Action.C
            return Action.C if coop_frac >= 0.5 else Action.D
        self.probe_counter += 1
        if self.probe_counter % 3 == 0:
            return Action.C
        return Action.D

class Strategy_COLLECTIVE_5(BaseStrategy):
    """
    Sustainable Trigger with Generous Recovery:
    cooperate by default, tolerate isolated defections, punish majority
    defection for at most 2 rounds, cooperate to rebuild critical stock,
    defect on the last round.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_count = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        if t == r - 1:
            return Action.D if current_stock > 0 else Action.C
        if cap > 0 and current_stock < 0.3 * cap:
            return Action.C
        coop_last = int(history.opponent_cooperators[-1]) + int(history.my_actions[-1])
        coop_frac = coop_last / n if n > 0 else 1.0
        if t == r - 2:
            if coop_frac >= 0.5 and current_stock >= 0.6 * cap:
                return Action.C
            return Action.D
        if coop_frac >= (n - 1) / n:
            self.punish_count = 0
            return Action.C
        if coop_frac >= 0.5:
            self.punish_count = 0
            return Action.C
        if self.punish_count < 2:
            self.punish_count += 1
            return Action.D
        self.punish_count = 0
        return Action.C

class Strategy_COLLECTIVE_6(BaseStrategy):
    """
    Sustainable Trigger with Generous Recovery:
    - Cooperate by default; defect last round.
    - Brief punishment (1-2 rounds) when >=2 others defect.
    - Never punish when stock is critical (<20% capacity) - cooperate to rebuild.
    - Persistent-exploitation guard: defect while others' recent defection rate > 60%.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_rounds = 0
        self.guard_active = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        opp = max(n - 1, 1)
        if t == 0:
            return Action.C
        coops_last = history.opponent_cooperators[-1]
        coop_frac = coops_last / opp
        defectors = opp - coops_last
        critical = current_stock < 0.2 * cap
        tolerant_thresh = (n - 2) / opp
        window = history.opponent_cooperators[-5:]
        total_slots = len(window) * opp
        if total_slots > 0:
            defect_rate = 1.0 - float(np.sum(window)) / total_slots
        else:
            defect_rate = 0.0
        if self.guard_active:
            if coop_frac >= tolerant_thresh or critical:
                self.guard_active = False
        elif defect_rate > 0.6 and (not critical):
            self.guard_active = True
        if self.punish_rounds > 0 and (coop_frac >= tolerant_thresh or critical):
            self.punish_rounds = 0
        if t == r - 1:
            return Action.D
        if critical:
            self.punish_rounds = 0
            return Action.C
        if t == r - 2:
            return Action.C if coop_frac >= 0.5 else Action.D
        if self.punish_rounds > 0:
            self.punish_rounds -= 1
            return Action.D
        if self.guard_active:
            return Action.D
        if defectors <= 1:
            return Action.C
        self.punish_rounds = (2 if defectors > n / 2 else 1) - 1
        return Action.D

class Strategy_COLLECTIVE_7(BaseStrategy):
    """Sustainable Trigger with Generous Recovery (STGR)."""

    def __init__(self, game_description: CommonPoolDescription):
        self.gd = game_description
        self.punish = 0
        self.just_finished = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.gd.n_players
        r = self.gd.n_rounds
        cap = float(self.gd.capacity)
        t = history.round_number
        if t == r - 1:
            return Action.D
        if current_stock < 0.2 * cap:
            if self.punish > 0:
                self.punish -= 1
                self.just_finished = self.punish == 0
            return Action.C
        if self.punish > 0:
            self.punish -= 1
            self.just_finished = self.punish == 0
            return Action.D
        if self.just_finished:
            self.just_finished = False
            return Action.C
        if t == 0:
            return Action.C
        d_last = n - 1 - int(history.opponent_cooperators[-1])
        if t == r - 2:
            if d_last == 0 and current_stock >= 0.5 * cap:
                return Action.C
            return Action.D
        threshold = 0 if n == 2 else math.ceil((n - 1) / 3)
        if d_last > threshold:
            self.punish = max(0, min(2, r - t - 3))
            return Action.D
        return Action.C

class Strategy_COLLECTIVE_8(BaseStrategy):
    """
    Sustainable Trigger with Generous Recovery:
    cooperate by default, punish widespread defection for one round,
    conserve unconditionally near collapse, defect in final round.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punishing = False
        self.prev_stock = float(game_description.capacity)

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        prev = self.prev_stock
        self.prev_stock = current_stock
        if t == r - 1:
            return Action.D
        if current_stock < 0.15 * cap:
            return Action.C
        if t == 0:
            return Action.C
        d = n - 1 - int(history.opponent_cooperators[-1])
        threshold = max(1, math.ceil((n - 1) / 3))
        if t == r - 2:
            return Action.C if d < n / 2 else Action.D
        if self.punishing:
            self.punishing = False
            return Action.D
        if d > threshold:
            self.punishing = True
            return Action.D
        return Action.C

class Strategy_PROSOCIAL_1(BaseStrategy):
    """Generous Stock-Guardian Tit-for-Tat."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punishing = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        t = history.round_number
        if t == 0:
            return Action.C
        if current_stock < 0.2 * gd.capacity:
            return Action.C
        n_opp = max(gd.n_players - 1, 1)
        coop_prev = history.opponent_cooperators[-1] / n_opp
        if t == gd.n_rounds - 1:
            avg = float(np.mean(history.opponent_cooperators)) / n_opp
            if avg >= 0.5 and current_stock >= 0.5 * gd.capacity:
                return Action.C
            return Action.D
        if self.punishing > 0:
            self.punishing -= 1
            return Action.D
        if coop_prev < 0.5:
            self.punishing = 1
            return Action.D
        return Action.C

class Strategy_PROSOCIAL_2(BaseStrategy):
    """
    Generous Threshold Tit-for-Tat with Stock Guardianship.
    Cooperates by default, protects depleted stock, punishes briefly
    and proportionally, always probes with C after punishment.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish = 0
        self.just_punished = False
        self.saw_defection_last_round = False
        self.persistent_defection = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t == 0:
            return Action.C
        coop_prev = int(history.opponent_cooperators[-1])
        defectors_prev = n - 1 - coop_prev
        if defectors_prev > (n - 1) / 2.0:
            self.persistent_defection += 1
        else:
            self.persistent_defection = 0
        if current_stock < 0.2 * cap:
            self.saw_defection_last_round = defectors_prev > 0
            return Action.C
        if t == r - 1:
            if coop_prev >= n - 1 or current_stock < 0.5 * cap:
                return Action.C
            return Action.D
        if self.punish > 0:
            self.punish -= 1
            if self.punish == 0:
                self.just_punished = True
            self.saw_defection_last_round = defectors_prev > 0
            return Action.D
        if self.just_punished:
            self.just_punished = False
            self.saw_defection_last_round = defectors_prev > 0
            return Action.C
        prev_saw = self.saw_defection_last_round
        self.saw_defection_last_round = defectors_prev > 0
        if defectors_prev == 0:
            return Action.C
        threshold = math.ceil((n - 1) / 3)
        if defectors_prev <= threshold:
            if prev_saw:
                self.punish = 0
                self.just_punished = True
                return Action.D
            return Action.C
        self.punish = 1 if self.persistent_defection < 3 else 2
        return Action.D

class Strategy_PROSOCIAL_3(BaseStrategy):
    """Generous Conditional Stewardship."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.pun = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        if t == 0:
            return Action.C
        last_coop = int(history.opponent_cooperators[-1])
        n_opp = max(n - 1, 1)
        if t == r - 1:
            return Action.C if last_coop >= (n - 1) / 2 else Action.D
        if current_stock < 0.2 * cap:
            return Action.C
        if self.pun > 0:
            self.pun -= 1
            return Action.D
        f = last_coop / n_opp
        if f >= 0.5:
            return Action.C
        if random.random() < f + 0.1:
            return Action.C
        self.pun = 1
        return Action.D

class Strategy_PROSOCIAL_4(BaseStrategy):
    """
    Generous Threshold Reciprocator with Stock Guardian:
    - Cooperates by default; punishes proportionally (with 10% generosity) for one round.
    - Never defects when stock < 40% of capacity; partial guardianship at 40-70%.
    - Rewards cooperative groups on the last round.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.defect_debt = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        if current_stock <= 0 or current_stock < 0.4 * cap:
            self.defect_debt = 0
            return Action.C
        n_opp = max(1, n - 1)
        coop_last = history.opponent_cooperators[-1]
        coop_rate_last = coop_last / n_opp
        if t == r - 1:
            return Action.C if coop_rate_last >= 0.5 else Action.D
        if self.defect_debt > 0:
            self.defect_debt -= 1
            return Action.D
        m = n_opp - coop_last
        if m == 0:
            return Action.C
        p_punish = max(0.0, m / n_opp - 0.1)
        if random.random() < p_punish:
            if current_stock < 0.7 * cap and random.random() < 0.5:
                return Action.C
            self.defect_debt = 0
            return Action.D
        return Action.C

class Strategy_PROSOCIAL_5(BaseStrategy):
    """
    Generous Stock-Guardian Tit-for-Tat:
    Cooperates by default, protects fragile stock, mildly punishes
    isolated defection probabilistically, escalates bounded punishment
    for widespread defection with probing, forgiving resets.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_remaining = 0
        self.punish_length = 1
        self.probing = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        if current_stock <= 0 or current_stock < 0.2 * cap:
            return Action.C
        n_opp = max(n - 1, 1)
        defectors_last = n_opp - int(history.opponent_cooperators[-1])
        f = defectors_last / n_opp
        if t == r - 1:
            return Action.C if f <= 0.5 else Action.D
        if r <= 3:
            return Action.C if f <= 0.5 else Action.D
        if self.punish_remaining > 0:
            self.punish_remaining -= 1
            if self.punish_remaining == 0:
                self.probing = True
            return Action.D
        if self.probing:
            self.probing = False
            if f > 0.34:
                self.punish_length = min(self.punish_length + 1, 3)
                self.punish_remaining = self.punish_length - 1
                if self.punish_remaining == 0:
                    self.probing = True
                return Action.D
            else:
                self.punish_length = 1
                return Action.C
        if f == 0:
            return Action.C
        if f <= 0.34:
            return Action.C if random.random() < 0.8 else Action.D
        self.punish_remaining = self.punish_length - 1
        if self.punish_remaining == 0:
            self.probing = True
        return Action.D

class Strategy_PROSOCIAL_6(BaseStrategy):
    """
    Generous Threshold Tit-for-Tat with Stock Guardianship.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.defect_streak = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        opp = max(n - 1, 1)
        if t == 0:
            return Action.C
        f_prev = history.opponent_cooperators[-1] / opp
        if t == r - 1:
            if f_prev >= 0.5 and current_stock >= 0.5 * cap:
                return Action.C
            return Action.D
        if current_stock < 0.2 * cap:
            self.defect_streak = 0
            return Action.C
        if f_prev >= 0.5:
            self.defect_streak = 0
            return Action.C
        if t >= 2 and f_prev > history.opponent_cooperators[-2] / opp:
            self.defect_streak = 0
            return Action.C
        if self.defect_streak >= 2:
            self.defect_streak = 0
            return Action.C
        self.defect_streak += 1
        return Action.D

class Strategy_PROSOCIAL_7(BaseStrategy):
    """
    Generous Threshold Tit-for-Tat with Stock Guardianship.
    Cooperates when stock is low, punishes briefly and probabilistically,
    defects in last round only against proven defectors.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.P = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        n_opp = max(n - 1, 1)
        if t == 0:
            return Action.C
        if current_stock < cap / 2:
            return Action.C
        if t == r - 1:
            recent = history.opponent_cooperators[-3:]
            if any((c < n - 1 for c in recent)):
                return Action.D
            return Action.C
        if self.P > 0:
            self.P -= 1
            return Action.D
        d = n - 1 - int(history.opponent_cooperators[-1])
        if d == 0:
            return Action.C
        if t >= 2:
            d_prev = n - 1 - int(history.opponent_cooperators[-2])
            if d > (n - 1) / 2 and d_prev > (n - 1) / 2:
                return Action.D
        if random.random() < max(0.0, (d - 0.5) / n_opp):
            self.P = 1
            return Action.D
        return Action.C

class Strategy_PROSOCIAL_8(BaseStrategy):
    """
    Sustainable Generous Tit-for-Tat with Stock Guardrails.
    Cooperates when stock is fragile, reciprocates majority cooperation,
    punishes briefly with probabilistic forgiveness.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.p = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        if current_stock < 0.4 * gd.capacity:
            return Action.C
        t = history.round_number
        if t == 0:
            return Action.C
        opps = max(gd.n_players - 1, 1)
        f = history.opponent_cooperators[-1] / opps
        if t == gd.n_rounds - 1:
            return Action.C if f >= 0.5 else Action.D
        if self.p > 0:
            self.p -= 1
            return Action.D
        if f >= 0.5:
            return Action.C
        if random.random() < 0.2:
            return Action.C
        self.p = 1
        return Action.D

class Strategy_ALTRUISTIC_1(BaseStrategy):
    """
    Guardian: unconditionally cooperate every round to sustain the commons.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_ALTRUISTIC_2(BaseStrategy):
    """
    Steward: always cooperates, except in the final round when the previous
    round had zero cooperating opponents (harmless defection).
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        if t == self.game_description.n_rounds - 1:
            if t > 0 and history.opponent_cooperators[-1] == 0:
                return Action.D
        return Action.C

class Strategy_ALTRUISTIC_3(BaseStrategy):
    """
    Steadfast Steward: unconditional cooperation in every round and state,
    since cooperation always maximizes group welfare.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_ALTRUISTIC_4(BaseStrategy):
    """
    Guardian of the Commons: unconditionally cooperates every round to
    maximize collective welfare and resource sustainability, regardless
    of opponent behavior or stock level.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_ALTRUISTIC_5(BaseStrategy):
    """
    Guardian Strategy: unconditional cooperation every round, regardless of
    history, stock level, or round number. Prioritizes stock health and
    others' welfare; never retaliates or exploits.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_ALTRUISTIC_6(BaseStrategy):
    """
    Guardian strategy: unconditional cooperation to sustain the commons.
    Always plays C; performs an informational crisis check only.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        cap = self.game_description.capacity
        if n > 0 and cap > 0:
            if history.round_number == 0:
                d = 0
            else:
                d = max(0, n - 1 - int(history.opponent_cooperators[-1]))
            S = current_stock
            T = S / (2 * n) + d * (S / n) + (n - 1 - d) * (S / (2 * n))
            R = max(0.0, S - T)
            _projected = min(R + 2 * R * (1 - R / cap), cap)
        return Action.C

class Strategy_ALTRUISTIC_7(BaseStrategy):
    """
    Guardian Strategy: always cooperate, never retaliate.
    Cooperation is the minimal-consumption action, so it always best preserves the stock.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_ALTRUISTIC_8(BaseStrategy):
    """Guardian: unconditional cooperation in all rounds and states."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        return Action.C

class Strategy_BENEVOLENT_1(BaseStrategy):
    """
    Generous Sustainable Trigger: cooperate by default, protect low stock,
    forgive isolated defection probabilistically, punish briefly (1-2 rounds),
    then offer an unconditional olive branch.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish = 0
        self.just_ended_punishment = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        if current_stock < 0.15 * cap:
            return Action.C
        d = n - 1 - int(history.opponent_cooperators[-1])
        if t == r - 1:
            if current_stock < 0.1 * cap:
                return Action.C
            return Action.C if d <= (n - 1) / 2 else Action.D
        if self.punish > 0:
            self.punish -= 1
            if self.punish == 0:
                self.just_ended_punishment = True
            return Action.D
        if d == 0:
            self.just_ended_punishment = False
            return Action.C
        if self.just_ended_punishment:
            self.just_ended_punishment = False
            return Action.C
        if n > 1 and random.random() < 0.5 * max(0.0, 1 - d / (n - 1)):
            return Action.C
        threshold = math.ceil((n - 1) / 2)
        self.punish = (2 if d >= threshold else 1) - 1
        return Action.D

class Strategy_BENEVOLENT_2(BaseStrategy):
    """Generous Stock-Guardian Tit-for-Tat."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punished_last_round = False
        self.consecutive_d = 0
        self.prev_stock = None

    def _play(self, action: Action) -> Action:
        if action == Action.C:
            self.punished_last_round = False
            self.consecutive_d = 0
        else:
            self.consecutive_d += 1
        return action

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        K = self.game_description.capacity
        t = history.round_number
        prev = self.prev_stock
        self.prev_stock = current_stock
        if t == 0:
            return self._play(Action.C)
        coop_prev = int(history.opponent_cooperators[-1])
        opp = max(n - 1, 1)
        if current_stock < 0.2 * K:
            return self._play(Action.C)
        if t == r - 1:
            if coop_prev >= math.ceil(opp / 2):
                return self._play(Action.C)
            return self._play(Action.D)
        if prev is not None and current_stock > prev:
            return self._play(Action.C)
        if coop_prev == 0:
            if self.consecutive_d % 3 == 2:
                return self._play(Action.C)
            return self._play(Action.D)
        if coop_prev / opp >= 0.5:
            return self._play(Action.C)
        if self.punished_last_round:
            return self._play(Action.C)
        self.punished_last_round = True
        self.consecutive_d += 1
        return Action.D

class Strategy_BENEVOLENT_3(BaseStrategy):
    """
    Generous Stock-Guardian Tit-for-Tat:
    Cooperates first; always cooperates if stock fraction < 0.4; cooperates when
    majority of opponents cooperated; otherwise defects with probability
    proportional to defection level; offers olive branch after own defection;
    benevolent last round (no exploitation of full cooperators).
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        t = history.round_number
        if t == 0:
            return Action.C
        cap = gd.capacity if gd.capacity > 0 else 1.0
        f = current_stock / cap
        n_opp = max(gd.n_players - 1, 1)
        coop_last = int(history.opponent_cooperators[-1])
        k = coop_last / n_opp
        threshold = math.ceil(n_opp / 2)
        if f < 0.4:
            return Action.C
        if t == gd.n_rounds - 1:
            if coop_last >= n_opp and f >= 0.8:
                return Action.C
            if coop_last < threshold:
                return Action.D
            return Action.C
        if t >= 2 and (not history.my_actions[-1]):
            if history.opponent_cooperators[-1] >= history.opponent_cooperators[-2]:
                return Action.C
        if coop_last >= threshold:
            return Action.C
        if random.random() < k:
            return Action.C
        return Action.D

class Strategy_BENEVOLENT_4(BaseStrategy):
    """
    Generous Stock-Guardian Tit-for-Tat: cooperates by default, protects low
    stock, retaliates proportionally and briefly, forgives generously, and
    refuses endgame exploitation of cooperators.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.was_low = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        n = gd.n_players
        r = gd.n_rounds
        cap = float(gd.capacity)
        t = history.round_number
        if t == 0:
            return Action.C
        if current_stock <= 0:
            return Action.C
        if current_stock < 0.2 * cap:
            self.was_low = True
            if t < r - 1:
                return Action.C
        n_opp = max(n - 1, 1)
        defectors_last = n_opp - int(history.opponent_cooperators[-1])
        if t == r - 1:
            if current_stock >= 0.5 * cap and defectors_last <= (n - 1) / 2:
                return Action.C
            return Action.D
        if self.was_low and current_stock > 0.6 * cap:
            self.was_low = False
            return Action.C
        f = defectors_last / n_opp
        if f <= 1 / 3:
            return Action.C
        if t >= 2 and (not history.my_actions[-1]) and (not history.my_actions[-2]):
            return Action.C
        if random.random() < 0.1:
            return Action.C
        return Action.D if random.random() < f else Action.C

class Strategy_BENEVOLENT_5(BaseStrategy):
    """
    Generous Stock-Guardian Tit-for-Tat:
    Cooperates by default, defects one round after majority defection,
    tolerates minority defection up to 2 consecutive rounds, and always
    cooperates when stock < 40% of capacity.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.P = 0
        self.streak = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.C
        d_prev = n - 1 - int(history.opponent_cooperators[-1])
        half = (n - 1) / 2.0
        fragile = current_stock < 0.4 * cap
        if fragile:
            self.P = max(self.P - 1, 0)
            return Action.C
        if t == r - 1:
            return Action.C if d_prev < half else Action.D
        if self.P > 0:
            self.P -= 1
            return Action.D
        if d_prev > half:
            return Action.D
        elif d_prev >= 1:
            self.streak += 1
            if self.streak >= 3:
                self.streak = 0
                return Action.D
            return Action.C
        else:
            self.streak = 0
            return Action.C

class Strategy_BENEVOLENT_6(BaseStrategy):
    """
    Generous Stock-Guardian Tit-for-Tat:
    Cooperate by default, mirror group's cooperation with generosity,
    always cooperate when stock < 40% of capacity, grant grace after
    full cooperation and stock recovery, no end-game defection against
    a cooperative group.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.prev_stock = None
        self.coop_grace = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        n_opp = max(n - 1, 1)
        if t == 0:
            self.prev_stock = current_stock
            return Action.C
        c = int(history.opponent_cooperators[-1])
        stock_increased = self.prev_stock is not None and current_stock > self.prev_stock
        self.prev_stock = current_stock
        if c >= n_opp:
            self.coop_grace = 2
        elif self.coop_grace > 0:
            self.coop_grace -= 1
        if current_stock < 0.4 * cap:
            return Action.C
        if c >= n_opp or self.coop_grace > 0:
            return Action.C
        if stock_increased and c >= math.ceil(n_opp / 3):
            return Action.C
        if c >= math.ceil(n_opp / 2):
            return Action.C
        if t == r - 1:
            avg_coop = float(np.mean(history.opponent_cooperators)) / n_opp
            if avg_coop >= 0.5:
                return Action.C
        if random.random() < 0.8:
            return Action.D
        return Action.C

class Strategy_BENEVOLENT_7(BaseStrategy):
    """Generous Stock-Guardian Tit-for-Tat."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.forgive_counter = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        if t == 0:
            return Action.C
        if current_stock < 0.2 * cap:
            return Action.C
        k = int(history.opponent_cooperators[-1])
        if t == r - 1:
            if k >= (n - 1) / 2 or current_stock < 0.5 * cap:
                return Action.C
            return Action.D
        if k >= math.ceil((n - 1) / 2):
            self.forgive_counter = 0
            return Action.C
        if current_stock >= 0.9 * cap:
            return Action.C
        self.forgive_counter += 1
        if self.forgive_counter >= 3:
            self.forgive_counter = 0
            return Action.C
        return Action.D

class Strategy_BENEVOLENT_8(BaseStrategy):
    """Generous Stock-Guardian Tit-for-Tat."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_count = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        gd = self.game_description
        n_opp = max(gd.n_players - 1, 1)
        if t == 0:
            return Action.C
        if current_stock < 0.4 * gd.capacity:
            return Action.C
        f = history.opponent_cooperators[-1] / n_opp
        if t == gd.n_rounds - 1:
            return Action.D if f < 0.5 else Action.C
        f_improved = False
        if t >= 2:
            f_prev2 = history.opponent_cooperators[-2] / n_opp
            f_improved = f - f_prev2 >= 1.0 / n_opp
        if f >= 0.5:
            self.punish_count = 0
            return Action.C
        if f_improved:
            self.punish_count = 0
            return Action.C
        if self.punish_count > 0 and self.punish_count % 3 == 0:
            self.punish_count += 1
            return Action.C
        self.punish_count += 1
        return Action.D

class Strategy_SELFISH_1(BaseStrategy):
    """Sustainable Extraction with Endgame Grab."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.strikes = 0
        self.fullC_count = 0
        self.exploit_enabled = True
        self.last_was_exploit = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        n, r, cap = (gd.n_players, gd.n_rounds, gd.capacity)
        t = history.round_number
        if t == 0:
            self.strikes = 0
            self.fullC_count = 0
            self.exploit_enabled = True
            self.last_was_exploit = False
            return Action.C
        c_prev = int(history.opponent_cooperators[-1])
        if t == r - 1:
            return Action.D
        if t == r - 2:
            return Action.C if n == 2 and c_prev == 1 else Action.D
        rho = c_prev / (n - 1) if n > 1 else 1.0
        if self.last_was_exploit and rho < 1:
            self.exploit_enabled = False
        exploit_now = False
        if current_stock < 0.2 * cap:
            self.last_was_exploit = False
            return Action.D
        if rho < 0.5:
            self.strikes += 1
        elif self.strikes >= 2 and current_stock >= 0.6 * cap:
            self.strikes = 0
        elif self.strikes < 2:
            self.strikes = 0
        if self.strikes >= 2:
            self.last_was_exploit = False
            return Action.D
        if rho == 1 and current_stock >= 0.9 * cap and (t < r - 3) and self.exploit_enabled:
            self.fullC_count += 1
            if self.fullC_count % 4 == 0:
                self.last_was_exploit = True
                return Action.D
        self.last_was_exploit = False
        return Action.C

class Strategy_SELFISH_2(BaseStrategy):
    """
    Sustainable Extraction with Generous Trigger:
    Cooperate to sustain the pool while opponents mostly cooperate and stock is
    healthy; defect in the endgame, when stock collapses, or when opponents
    drain the pool heavily.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = n - 1
        if t == r - 1:
            return Action.D
        if t == 0:
            return Action.C
        if t >= r - 2:
            if n == 2 and current_stock >= cap and all((int(c) == opp for c in history.opponent_cooperators)):
                return Action.C
            return Action.D
        if t >= r - 3 and current_stock < 0.4 * cap:
            return Action.D
        d_last = opp - int(history.opponent_cooperators[-1])
        f = d_last / opp if opp > 0 else 0.0
        if current_stock < 0.25 * cap:
            if f == 0.0 and t <= r - 4:
                return Action.C
            return Action.D
        if f <= 1.0 / n:
            return Action.C
        if f > 0.5:
            return Action.D
        k = min(3, t)
        recent_coop = history.opponent_cooperators[-k:]
        if opp > 0:
            recent = float(np.mean([(opp - int(c)) / opp for c in recent_coop]))
        else:
            recent = 0.0
        if current_stock >= 0.6 * cap and recent <= 1.0 / 3.0:
            return Action.C
        return Action.D

class Strategy_SELFISH_3(BaseStrategy):
    """
    Sustainable Extraction with Threshold Retaliation.
    Cooperate to preserve stock; defect at end-game, when others drain
    the pool, or occasionally skim a near-full pool.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        n = gd.n_players
        r = gd.n_rounds
        cap = gd.capacity
        t = history.round_number
        stock = current_stock
        if t == r - 1:
            return Action.D
        n_opp = max(n - 1, 1)
        if t > 0:
            recent = history.opponent_cooperators[-3:]
            coop_rate = float(np.mean(recent)) / n_opp
            defectors_last = n_opp - int(history.opponent_cooperators[-1])
        else:
            coop_rate = 1.0
            defectors_last = 0
        if t == r - 2:
            s_rem = stock - stock / n - (n - 1) * (coop_rate * stock / (2 * n) + (1 - coop_rate) * stock / n)
            s_rem = max(s_rem, 0.0)
            growth = 2 * s_rem * (1 - s_rem / cap) if cap > 0 else 0.0
            next_stock = min(s_rem + growth, cap)
            return Action.D if next_stock >= 0.25 * cap else Action.C
        if t == 0:
            return Action.C
        if stock < 0.2 * cap:
            return Action.C
        if defectors_last >= math.ceil((n - 1) / 2):
            return Action.D
        if stock >= 0.9 * cap and defectors_last <= 1 and (random.random() < 1.0 / r):
            return Action.D
        return Action.C

class Strategy_SELFISH_4(BaseStrategy):
    """
    Sustainable Trigger with Endgame Exploitation.
    Cooperates to preserve stock as a selfish investment; defects in endgame,
    on dead pools, and to punish widespread defection.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_counter = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == r - 1:
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if self.punish_counter > 0:
            self.punish_counter -= 1
            return Action.D
        d = n - 1 - int(history.opponent_cooperators[-1])
        if t == r - 2:
            return Action.C if d <= 1 and current_stock >= 0.75 * cap else Action.D
        if d == 0:
            return Action.C
        if d <= math.ceil(n / 4):
            return Action.C if current_stock >= 0.5 * cap else Action.D
        self.punish_counter = 1
        return Action.D

class Strategy_SELFISH_5(BaseStrategy):
    """
    Sustainable Trigger with Endgame Exploitation:
    generous tit-for-tat on majority, collapse guard, endgame defection,
    and occasional opportunistic skim at full stock.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.last_skim = -10
        self.defect_streak = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = current_stock

        def defect():
            self.defect_streak += 1
            return Action.D

        def coop():
            self.defect_streak = 0
            return Action.C
        if t == r - 1:
            return defect()
        if t == r - 2 and (n >= 3 or S >= 0.5 * cap):
            return defect()
        if S < 0.15 * cap:
            return coop()
        if t == 0:
            return coop()
        opp = max(n - 1, 1)
        f = history.opponent_cooperators[-1] / opp
        if f >= 0.5:
            if S >= cap * 0.999 and f == 1.0 and (t - self.last_skim >= 3) and (t < r - 3) and (cap > 0):
                s_rem = S - (n - 1) * S / (2 * n) - S / n
                s_new = min(s_rem + 2 * s_rem * (1 - s_rem / cap), cap)
                if s_new >= 0.9 * cap:
                    self.last_skim = t
                    return defect()
            return coop()
        else:
            if self.defect_streak >= 1 and t < r - 3 and (random.random() < 0.1):
                return coop()
            return defect()

class Strategy_SELFISH_6(BaseStrategy):
    """
    Sustainable Extraction with Endgame Grab: cooperate to sustain the stock
    while opponents mostly cooperate; defect on endgame, dead pools, or when
    smoothed defection rate is too high.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.d_hat = 0.0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = current_stock
        if t == 0:
            self.d_hat = 0.0
            if t == r - 1 or (cap > 0 and S < 0.05 * cap):
                return Action.D
            return Action.C
        coop = int(history.opponent_cooperators[-1])
        my_coop = bool(history.my_actions[-1])
        d_prev = n - 1 - coop + (0 if my_coop else 1)
        self.d_hat = 0.6 * (d_prev / n if n > 0 else 0.0) + 0.4 * self.d_hat
        if t == r - 1:
            return Action.D
        if cap > 0 and S < 0.05 * cap:
            return Action.D
        if t == r - 2 and (S < 0.25 * cap or d_prev >= n / 2):
            return Action.D
        if d_prev <= 1 and S >= 0.6 * cap:
            return Action.C
        if self.d_hat > 0.5:
            return Action.D
        if self.d_hat > 0.25 and S < 0.5 * cap:
            return Action.D
        return Action.C

class Strategy_SELFISH_7(BaseStrategy):
    """
    Sustainable Extraction with Endgame Grab:
    - Defect in last round; mostly defect in second-to-last.
    - Cooperate to protect collapsing stock (S < 0.2*cap) when future remains.
    - Majority-conditional cooperation otherwise, with re-probe after 3 defects
      and rare opportunistic skims when all opponents cooperate at high stock.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        R = r - t
        S = current_stock
        coop_prev = int(history.opponent_cooperators[-1]) if t > 0 else n - 1
        if R <= 1:
            return Action.D
        if R == 2:
            if S < cap / 2 and coop_prev >= n - 1:
                return Action.C
            return Action.D
        if S < 0.2 * cap:
            return Action.C
        if t == 0:
            return Action.C
        if coop_prev >= math.ceil((n - 1) / 2):
            if coop_prev == n - 1 and S >= 0.9 * cap and (random.random() < 1.0 / max(r, 1)):
                return Action.D
            return Action.C
        if t >= 3 and (not any(history.my_actions[-3:])) and (S >= 0.6 * cap):
            return Action.C
        return Action.D

class Strategy_SELFISH_8(BaseStrategy):
    """
    Sustainable Extraction with Contingent Punishment (SECP).
    Cooperates when majority cooperated; defects near endgame, on dead pools,
    or to punish low cooperation, with recovery and probe overrides.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == r - 1:
            return Action.D
        if t == r - 2 and n <= 4:
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        c = history.opponent_cooperators[-1]
        denom = max(n - 1, 1)
        if c / denom >= 0.5:
            return Action.C
        rounds_left = r - t
        if current_stock < 0.4 * cap and rounds_left >= 3:
            return Action.C
        if t >= 2 and (not history.my_actions[-1]) and (not history.my_actions[-2]) and (rounds_left >= 3) and (current_stock >= 0.2 * cap):
            return Action.C
        return Action.D

class Strategy_SELFINTERESTED_1(BaseStrategy):
    """
    Sustainable Trigger with Endgame Defection:
    Cooperate while opponents mostly cooperate; punish-forgive intermediate
    defection (max 2 cycles); grim-defect on heavy defection; defect at endgame
    and when stock is nearly dead; recovery override to rejoin cooperation.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.mode = 'NORMAL'
        self.cycles_used = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == r - 1:
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        n_opp = max(n - 1, 1)
        c_prev = int(history.opponent_cooperators[-1])
        f = c_prev / n_opp
        if t == r - 2:
            fully_coop = n == 2 and all((int(x) == n_opp for x in history.opponent_cooperators)) and all((bool(a) for a in history.my_actions))
            if not fully_coop:
                return Action.D
            return Action.C
        if self.mode == 'GRIM':
            if current_stock > 0.6 * cap and f == 1.0:
                self.mode = 'NORMAL'
                return Action.C
            return Action.D
        if self.mode == 'PUNISH':
            self.mode = 'NORMAL'
            return Action.C
        threshold = (n - 2) / n_opp
        if f >= threshold:
            return Action.C
        if f < 0.5:
            self.mode = 'GRIM'
            return Action.D
        self.cycles_used += 1
        if self.cycles_used > 2:
            self.mode = 'GRIM'
            return Action.D
        self.mode = 'PUNISH'
        return Action.D

class Strategy_SELFINTERESTED_2(BaseStrategy):
    """
    Sustainable Trigger with Endgame Defection:
    cooperate to sustain stock, punish briefly, lock out on persistent
    defection, defect at endgame or when the pool is collapsed.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punished_last_round = False
        self.locked_out = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = max(n - 1, 1)
        threshold = (n - 2) / opp
        if t == r - 1:
            return Action.D
        if t == 0:
            return Action.C
        if current_stock < 0.1 * cap:
            return Action.D
        f = history.opponent_cooperators[-1] / opp
        if t == r - 2:
            if n >= 3 or current_stock < cap / 2:
                return Action.D
            if f >= 1.0:
                self.punished_last_round = False
                return Action.C
            return Action.D
        if t >= 3:
            recent = history.opponent_cooperators[-3:]
            if all((c / opp < 0.5 for c in recent)):
                self.locked_out = True
        if self.locked_out or self.punished_last_round:
            if current_stock >= 0.9 * cap and f >= threshold:
                self.locked_out = False
                self.punished_last_round = False
                return Action.C
        if self.locked_out:
            return Action.D
        if self.punished_last_round:
            self.punished_last_round = False
            return Action.C
        if f >= threshold:
            self.punished_last_round = False
            return Action.C
        self.punished_last_round = True
        return Action.D

class Strategy_SELFINTERESTED_3(BaseStrategy):
    """
    Sustainable trigger with endgame defection, forgiving threshold rule,
    and occasional exploitation probes against unanimous cooperators.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.unanimous_streak = 0
        self.probe_ready = True

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        n_opp = max(n - 1, 1)
        if t > 0:
            coop_frac = history.opponent_cooperators[-1] / n_opp
            if coop_frac >= 1.0:
                self.unanimous_streak += 1
            else:
                self.unanimous_streak = 0
                self.probe_ready = True
        else:
            coop_frac = 1.0
        if t == r - 1:
            return Action.D
        if t == r - 2:
            return Action.C if n == 2 and coop_frac >= 0.5 else Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if self.probe_ready and self.unanimous_streak >= 3 and (current_stock >= cap * 0.999) and (t < r - 4):
            self.probe_ready = False
            self.unanimous_streak = 0
            return Action.D
        if coop_frac >= 0.75:
            return Action.C
        if coop_frac >= 0.5 and current_stock >= 0.3 * cap:
            return Action.C
        return Action.D

class Strategy_SELFINTERESTED_4(BaseStrategy):
    """
    Sustainable Trigger with Endgame Defection:
    Generous tit-for-tat on the majority with collapse checks,
    endgame defection, forgiveness, and exploratory probing.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.consecutive_my_defects = 0

    def _act(self, action: Action) -> Action:
        if action == Action.D:
            self.consecutive_my_defects += 1
        else:
            self.consecutive_my_defects = 0
        return action

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t == r - 1:
            return self._act(Action.D)
        if t == r - 2:
            if n == 2 and current_stock >= cap:
                no_defect = True
                for k in range(max(0, t - 2), t):
                    if history.opponent_cooperators[k] < n - 1:
                        no_defect = False
                if t >= 1 and history.opponent_cooperators[-1] < n - 1:
                    no_defect = False
                if no_defect:
                    return self._act(Action.C)
            return self._act(Action.D)
        if current_stock < 0.1 * cap:
            return self._act(Action.D)
        if t >= 1:
            coop_opp = int(history.opponent_cooperators[-1])
            defect_opp = n - 1 - coop_opp
            consumption = current_stock / (2 * n) + coop_opp * current_stock / (2 * n) + defect_opp * current_stock / n
            remaining = max(0.0, current_stock - consumption)
            growth = 2.0 * remaining * (1.0 - remaining / cap) if cap > 0 else 0.0
            projected = min(remaining + growth, cap)
            if projected < 0.25 * cap:
                return self._act(Action.D)
        if t == 0:
            return self._act(Action.C)
        denom = max(1, n - 1)
        f = (n - 1 - int(history.opponent_cooperators[-1])) / denom
        theta = 0.25 if r - t <= 4 else 1.0 / 3.0
        if f <= theta:
            return self._act(Action.C)
        if self.consecutive_my_defects >= 3 and current_stock >= 0.5 * cap and (int(history.opponent_cooperators[-1]) >= math.ceil((n - 1) / 2)) and (r - t >= 4):
            return self._act(Action.C)
        return self._act(Action.D)

class Strategy_SELFINTERESTED_5(BaseStrategy):
    """
    Sustainable Trigger with Endgame Defection:
    cooperate with cooperative majorities, one-round punishments,
    3-strike permanent lockout, stock-recovery override, endgame defection.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.low_f_streak = 0
        self.lockout = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        f = 1.0
        if t > 0:
            opp = max(n - 1, 1)
            f = history.opponent_cooperators[-1] / opp
            if f < 0.5:
                self.low_f_streak += 1
            else:
                self.low_f_streak = 0
            if self.low_f_streak >= 3:
                self.lockout = True
        if t == r - 1:
            return Action.D
        if t == r - 2:
            if n == 2 and current_stock >= 0.5 * cap:
                opp = max(n - 1, 1)
                if all((c == opp for c in history.opponent_cooperators)):
                    return Action.C
            return Action.D
        if t == 0:
            return Action.C
        if current_stock < 0.15 * cap:
            return Action.D
        if self.lockout:
            return Action.D
        if current_stock < 0.4 * cap:
            return Action.C if f >= 0.3 else Action.D
        return Action.C if f >= 0.5 else Action.D

class Strategy_SELFINTERESTED_6(BaseStrategy):
    """
    Sustainable Trigger with Endgame Defection:
    forgiving trigger, recovery probes, hopeless-population override,
    dead-pool grab and endgame defection.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.consec_my_defects = 0
        self.rounds_since_probe = 999

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t > 0:
            if history.my_actions[-1]:
                self.consec_my_defects = 0
            else:
                self.consec_my_defects += 1
            self.rounds_since_probe += 1
        opp = max(1, n - 1)
        if t > 0:
            coop_rate = float(np.sum(history.opponent_cooperators)) / (opp * t)
            d_prev = opp - int(history.opponent_cooperators[-1])
        else:
            coop_rate = 1.0
            d_prev = 0

        def act(a):
            if a:
                self.rounds_since_probe = 0 if False else self.rounds_since_probe
            return Action.C if a else Action.D
        if t == r - 1:
            return Action.D
        if t == r - 2:
            return Action.C if n == 2 and coop_rate >= 0.8 else Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if t >= 3 and coop_rate < 0.25:
            return Action.D
        T = max(1, n // 3)
        if d_prev <= T:
            return Action.C
        if self.consec_my_defects >= 2 and current_stock >= 0.4 * cap and (self.rounds_since_probe >= 3):
            self.rounds_since_probe = 0
            return Action.C
        return Action.D

class Strategy_SELFINTERESTED_7(BaseStrategy):
    """Sustainable trigger with endgame defection."""

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        d_prev = 0
        if t > 0:
            d_prev = n - 1 - int(history.opponent_cooperators[-1])
        if t == r - 1:
            return Action.D
        if t == r - 2:
            return Action.C if n == 2 and d_prev == 0 else Action.D
        if current_stock < 0.1 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if d_prev == 0:
            return Action.C
        if d_prev >= math.ceil((n - 1) / 3):
            return Action.D
        return Action.C if current_stock >= 0.5 * cap else Action.D

class Strategy_SELFINTERESTED_8(BaseStrategy):
    """
    Sustainable Trigger with Endgame Harvest:
    conditional cooperation with one-shot olive branch, stock guards,
    and endgame defection.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.olive_pending = False
        self.olive_failed = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = max(n - 1, 1)
        if t >= 1 and self.olive_pending:
            f_now = history.opponent_cooperators[-1] / opp
            if f_now < 0.5:
                self.olive_failed = True
            else:
                self.olive_failed = False
            self.olive_pending = False
        E = 1 + (1 if n <= 3 else 0)
        if r - 1 - t < E:
            return Action.D
        if current_stock < 0.1 * cap:
            return Action.D
        if t == 0:
            return Action.C
        f = history.opponent_cooperators[-1] / opp
        if current_stock >= 0.9 * cap and f >= (n - 2) / opp:
            return Action.C
        if f >= 0.5:
            self.olive_failed = False
            return Action.C
        my_last = history.my_actions[-1]
        if not my_last and t >= 2 and (history.opponent_cooperators[-1] > history.opponent_cooperators[-2]) and (current_stock >= 0.5 * cap) and (not self.olive_failed):
            self.olive_pending = True
            return Action.C
        return Action.D

class Strategy_OPPORTUNISTIC_1(BaseStrategy):
    """
    Opportunistic Free-Rider with Sustainability Guardrails.
    Defects to exploit cooperators and in endgame; cooperates only as an
    investment to regenerate the pool or repair opponent cooperation.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.avg_coop = 0.0
        self.repair_rounds_left = 0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = max(n - 1, 1)
        if t == 0:
            return Action.D
        coop_rate = history.opponent_cooperators[-1] / opp
        if t == 1:
            self.avg_coop = coop_rate
        else:
            self.avg_coop = 0.7 * coop_rate + 0.3 * self.avg_coop
        rounds_left = r - t
        if t >= r - 2:
            return Action.D
        if t == r - 3 and n >= 4 and (current_stock >= 0.6 * cap):
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if self.repair_rounds_left > 0:
            if rounds_left >= 4:
                self.repair_rounds_left -= 1
                return Action.C
            self.repair_rounds_left = 0
        elif t >= 3 and rounds_left >= 4:
            if not history.my_actions[-2] or not history.my_actions[-3]:
                prev = history.opponent_cooperators[-3] / opp
                now = history.opponent_cooperators[-1] / opp
                if prev - now > 1.0 / opp:
                    self.repair_rounds_left = 1
                    return Action.C
        if self.avg_coop < 0.5:
            return Action.D
        high_thresh = (n - 1.5) / opp
        if self.avg_coop >= high_thresh:
            return Action.D if current_stock >= 0.5 * cap else Action.C
        return Action.D if current_stock >= 0.7 * cap else Action.C

class Strategy_OPPORTUNISTIC_2(BaseStrategy):
    """
    Opportunistic Free-Rider with Sustainability Guardrails:
    defect when stock can absorb it or future doesn't matter;
    cooperate only as a worthwhile investment.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.coop_rate = 1.0
        self.prev_stocks = []

    def _project(self, S, my_consumption):
        n = self.game_description.n_players
        cap = self.game_description.capacity
        others = (n - 1) * (self.coop_rate * S / (2 * n) + (1 - self.coop_rate) * S / n)
        S_rem = max(S - my_consumption - others, 0.0)
        growth = 2 * S_rem * (1 - S_rem / cap) if cap > 0 else 0.0
        return min(S_rem + growth, cap)

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = current_stock
        if t > 0 and n > 1:
            observed = history.opponent_cooperators[-1] / (n - 1)
            self.coop_rate = 0.5 * self.coop_rate + 0.5 * observed
        self.prev_stocks.append(S)
        if t >= r - 2:
            return Action.D
        if t == r - 3 and self.coop_rate < 0.5:
            return Action.D
        if S < 0.05 * cap:
            return Action.D
        S_next = self._project(S, S / n)
        S_next_C = self._project(S, S / (2 * n))
        if S_next >= 0.6 * cap:
            return Action.D
        if len(self.prev_stocks) >= 3 and self.coop_rate < 0.5 and (self.prev_stocks[-1] < self.prev_stocks[-2] < self.prev_stocks[-3]):
            return Action.D
        threshold = (n - 2) / (n - 1) if n > 1 else 0.0
        if S_next_C - S_next >= 0.1 * cap and self.coop_rate >= threshold and (r - t >= 3):
            return Action.C
        return Action.D

class Strategy_OPPORTUNISTIC_3(BaseStrategy):
    """
    Opportunistic Free-Rider with Sustainability Guardrails.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        if t == 0:
            return Action.D
        if t >= r - 2:
            return Action.D
        coop_last = int(history.opponent_cooperators[-1])
        my_prev = bool(history.my_actions[-1])
        if t == 1 and coop_last >= n - 1:
            return Action.C
        ratio = current_stock / cap if cap > 0 else 0.0
        if my_prev and coop_last >= n - 2:
            return Action.D
        if ratio >= 0.6:
            if coop_last >= math.ceil(n / 2):
                return Action.D
            return Action.D if random.random() < 0.5 else Action.C
        if ratio >= 0.3:
            return Action.D if coop_last == 0 else Action.C
        return Action.D

class Strategy_OPPORTUNISTIC_4(BaseStrategy):
    """
    Exploitative Sustainer: cooperates only enough to keep the stock alive,
    defects at endgame, when the pool is dead, when free-riding is safe,
    or when the pool collapses regardless; probes with periodic defection
    unless punished.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_until = -1
        self.last_probe_round = -1
        self.coop_before_probe = None

    def _next_stock(self, S, n_coop):
        n = self.game_description.n_players
        cap = self.game_description.capacity
        consumption = n_coop * S / (2 * n) + (n - n_coop) * S / n
        S_rem = max(S - consumption, 0.0)
        if cap <= 0:
            return 0.0
        growth = 2 * S_rem * (1 - S_rem / cap)
        return min(S_rem + growth, cap)

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = float(current_stock)
        if t > 0:
            k = int(history.opponent_cooperators[-1])
            if self.last_probe_round == t - 1 and self.coop_before_probe is not None and (self.coop_before_probe - k >= 2):
                self.punish_until = t + 4
        else:
            k = math.ceil((n - 1) / 2)
        if t >= r - 2 or S < 0.05 * cap:
            return Action.D
        if self._next_stock(S, k) >= 0.5 * cap:
            return Action.D
        if self._next_stock(S, k + 1) >= 0.35 * cap:
            if t % 4 == 3 and k >= n / 2 and (S >= 0.7 * cap) and (t >= self.punish_until):
                self.last_probe_round = t
                self.coop_before_probe = k
                return Action.D
            return Action.C
        return Action.D

class Strategy_OPPORTUNISTIC_5(BaseStrategy):
    """
    Opportunistic Skimmer: defects at endpoints, free-rides on cooperative
    fields, cooperates only when its restraint is pivotal to sustaining stock.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.p_hat = 0.5

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t > 0 and n > 1:
            coops = float(history.opponent_cooperators[-1])
            self.p_hat = 0.7 * self.p_hat + 0.3 * (coops / (n - 1))
        if t == 0 or t == r - 1:
            return Action.D
        health = current_stock / cap if cap > 0 else 0.0
        rounds_left = r - t
        if t == r - 2:
            if self.p_hat >= 0.8 and health > 0.6 and (n >= 4):
                return Action.C
            return Action.D
        if health < 0.2:
            return Action.D
        last_defectors = n - 1 - history.opponent_cooperators[-1]
        if last_defectors >= (n - 1) / 2 and health < 0.6:
            return Action.D
        if n > 0 and self.p_hat >= 0.9 * (n - 1) / n and (health > 0.5):
            return Action.D
        if health >= 0.95:
            return Action.D
        d_hat = (1.0 - self.p_hat) * (n - 1) + 1.0
        frac = 1.0 - (n + d_hat) / (2.0 * n)
        remaining = max(0.0, current_stock * frac)
        growth = 2.0 * remaining * (1.0 - remaining / cap) if cap > 0 else 0.0
        projected = min(remaining + growth, cap)
        if projected >= 0.5 * cap:
            return Action.D
        if rounds_left <= max(2, math.ceil(0.1 * r)) and (not (self.p_hat >= 0.8 and health > 0.6)):
            return Action.D
        return Action.C

class Strategy_OPPORTUNISTIC_6(BaseStrategy):
    """
    Exploitative Trigger-Rider: defect early/late and when free-riding pays,
    cooperate to rebuild stock, probe periodically and adapt to retaliation.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punishers = False
        self.bonus = 0.0
        self.last_probe_round = None
        self.f_before_probe = None

    def _f(self, history, idx):
        n_opp = max(1, self.game_description.n_players - 1)
        return history.opponent_cooperators[idx] / n_opp

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        n = gd.n_players
        r = gd.n_rounds
        K = gd.capacity if gd.capacity > 0 else 1.0
        t = history.round_number
        h = current_stock / K
        if self.last_probe_round is not None and t >= self.last_probe_round + 2:
            f_after = self._f(history, -1)
            if self.f_before_probe is not None:
                if self.f_before_probe - f_after > 0.3:
                    self.punishers = True
                elif abs(self.f_before_probe - f_after) < 1e-09:
                    self.bonus = min(1.0, self.bonus + 0.25)
            self.last_probe_round = None
            self.f_before_probe = None
        if r <= 3:
            return Action.D
        if t >= r - 2:
            return Action.D
        if t == 0:
            return Action.D
        if h < 0.15:
            return Action.C
        f = self._f(history, -1)
        if f >= 0.75 and h >= 0.5:
            return Action.D
        if f <= 0.25:
            return Action.D
        if t % 4 == 0 and (not self.punishers):
            self.last_probe_round = t
            self.f_before_probe = f
            return Action.D
        if h >= 0.6:
            p = min(1.0, 0.5 + 0.5 * f + self.bonus)
            return Action.D if random.random() < p else Action.C
        return Action.C

class Strategy_OPPORTUNISTIC_7(BaseStrategy):
    """
    Opportunistic Free-Rider with Sustainability Guardrails.
    Defects when endgame, dead stock, or others' cooperation absorbs it;
    cooperates only as an investment to keep the pool worth plundering.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = float(current_stock)
        R = r - t
        if t == 0:
            return Action.D
        if R <= 1 or (R == 2 and S >= 0.5 * cap):
            return Action.D
        if S < 0.15 * cap:
            return Action.D
        opp = max(n - 1, 1)
        k = min(3, t)
        recent = history.opponent_cooperators[-k:]
        p = float(np.mean(recent)) / opp
        if p < 1.0 / opp:
            return Action.D
        consumption = S / n + (n - 1) * (p * S / (2 * n) + (1 - p) * S / n)
        rem = max(S - consumption, 0.0)
        growth = 2 * rem * (1 - rem / cap) if cap > 0 else 0.0
        s_next = min(rem + growth, cap)
        if s_next >= 0.5 * cap:
            return Action.D
        if S >= 0.4 * cap and R >= 3:
            return Action.C
        if history.opponent_cooperators[-1] >= math.ceil(opp / 2):
            return Action.C
        return Action.D

class Strategy_OPPORTUNISTIC_8(BaseStrategy):
    """Exploitative Threshold Harvester."""

    def __init__(self, game_description: CommonPoolDescription):
        self.gd = game_description
        self.k = max(3, math.ceil(game_description.n_rounds / 5))

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        t = history.round_number
        n = self.gd.n_players
        r = self.gd.n_rounds
        cap = float(self.gd.capacity)
        if t == 0:
            return Action.C
        if t >= r - 1 or (t == r - 2 and current_stock >= 0.5 * cap):
            return Action.D
        if current_stock < 0.1 * cap:
            return Action.D
        opp = max(n - 1, 1)
        recent = history.opponent_cooperators[-3:]
        trend = float(np.mean(recent)) / opp
        if trend >= 0.8:
            if current_stock >= 0.8 * cap and t % self.k == 0:
                return Action.D
            elif current_stock >= 0.6 * cap:
                return Action.D
            return Action.C
        elif trend >= 0.5:
            return Action.C if current_stock < 0.5 * cap else Action.D
        else:
            if current_stock >= 0.7 * cap:
                return Action.D
            if r - t >= 4 and trend >= 0.25:
                return Action.C
            return Action.D

class Strategy_INDIVIDUALISTIC_1(BaseStrategy):
    """
    Harvest-Guard: sustainable extraction with contingent, escalating punishment,
    end-game defection, stock-collapse override, and grim fallback.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.punish_timer = 0
        self.escalation = 1
        self.minor_streak = 0
        self.just_punished = False
        self.grim = False

    def _start_punishment(self):
        self.punish_timer = self.escalation
        self.escalation = min(self.escalation + 1, 4)
        self.minor_streak = 0
        return Action.D

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t == 0:
            return Action.C
        if t >= r - 1:
            return Action.D
        if t == r - 2 and current_stock >= 0.5 * cap:
            return Action.D
        opp = max(n - 1, 1)
        d = opp - int(history.opponent_cooperators[-1])
        coop_last = int(history.opponent_cooperators[-1])
        if t >= r - 3 and coop_last / opp < 0.5:
            return Action.D
        if current_stock < 0.1 * cap:
            return Action.D
        if current_stock < 0.4 * cap:
            return Action.C if coop_last >= math.ceil(opp / 2) else Action.D
        total_coop = float(np.sum(history.opponent_cooperators))
        if self.grim or total_coop / (opp * t) < 0.3:
            self.grim = True
            return Action.D
        if self.punish_timer > 0:
            self.punish_timer -= 1
            if self.punish_timer == 0:
                self.just_punished = True
            return Action.D
        minor_thresh = (n - 1) // 3
        if self.just_punished:
            self.just_punished = False
            if d <= minor_thresh:
                if d == 0:
                    self.minor_streak = 0
                return Action.C
            return self._start_punishment()
        if d == 0:
            self.minor_streak = 0
            return Action.C
        if d <= minor_thresh:
            self.minor_streak += 1
            if self.minor_streak >= 3:
                return self._start_punishment()
            return Action.C
        return self._start_punishment()

class Strategy_INDIVIDUALISTIC_2(BaseStrategy):
    """
    Sustainable Extraction with Threshold Retaliation (SETR).
    Cooperates instrumentally when opponents cooperate and stock is healthy;
    defects at endgame, on depleted stock, against defecting majorities,
    as one-round punishment for cooperation drops, and as a periodic probe.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        opp = n - 1
        if t == r - 1:
            return Action.D
        if t == r - 2:
            if n >= 4:
                return Action.D
            if t == 0:
                return Action.C
            return Action.C if history.opponent_cooperators[-1] == opp else Action.D
        if t == 0:
            return Action.C
        rho = current_stock / cap if cap > 0 else 0.0
        f = history.opponent_cooperators[-1] / opp if opp > 0 else 1.0
        if rho < 0.2 or f < 0.5:
            return Action.D
        if t >= 2:
            drop = history.opponent_cooperators[-1] - history.opponent_cooperators[-2]
            if drop <= -math.ceil(0.25 * opp):
                return Action.D
        if n > 3 and rho >= 1.0 and (t >= 3) and (t % 4 == 3):
            if all((history.opponent_cooperators[-k] == opp for k in (1, 2, 3))):
                return Action.D
        return Action.C

class Strategy_INDIVIDUALISTIC_3(BaseStrategy):
    """
    Harvest-Guard: sustainable extraction with conditional punishment.
    Cooperates only to keep the stock high for future extraction; punishes
    defection waves and defects in the endgame.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.pun = 0
        self.last_stock = None
        self.last_action_was_c = False
        self.low_stock_defect = False

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        S = current_stock
        prev_stock = self.last_stock
        prev_was_c = self.last_action_was_c
        self.last_stock = S

        def ret(a: Action) -> Action:
            self.last_action_was_c = a == Action.C
            return a
        if t == r - 1:
            return ret(Action.D)
        if S < 0.05 * cap:
            return ret(Action.D)
        if t == 0:
            return ret(Action.C)
        opp = max(n - 1, 1)
        f = history.opponent_cooperators[-1] / opp
        if t == r - 2:
            return ret(Action.C if f >= 0.5 else Action.D)
        if t == r - 3 and f < 0.7:
            return ret(Action.D)
        if self.pun > 0:
            if f >= 0.7:
                self.pun = 0
            else:
                self.pun -= 1
                return ret(Action.D)
        if S >= 0.4 * cap:
            self.low_stock_defect = False
        if f >= 0.5 and S >= 0.4 * cap:
            return ret(Action.C)
        if f >= 0.5:
            if prev_was_c and prev_stock is not None and (S <= prev_stock):
                self.low_stock_defect = True
            if self.low_stock_defect:
                return ret(Action.D)
            return ret(Action.C)
        self.pun = 1
        return ret(Action.D)

class Strategy_INDIVIDUALISTIC_4(BaseStrategy):
    """
    Harvest-Guard: sustainable extraction with trigger response,
    endgame defection, stock-collapse override, conditional
    forgiveness, and periodic re-entry probes.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.consec_defects = 0
        self.probe_round = None
        self.no_probe_until = -1

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number

        def record(action, rule5_defect=False):
            if rule5_defect:
                self.consec_defects += 1
            else:
                self.consec_defects = 0
            return action
        if self.probe_round is not None and t == self.probe_round + 1:
            denom = max(n - 1, 1)
            if history.opponent_cooperators[-1] / denom >= 0.5:
                self.consec_defects = 0
            else:
                self.no_probe_until = t + 4
            self.probe_round = None
        if t == 0:
            return record(Action.C)
        last_coop = int(history.opponent_cooperators[-1])
        if t == r - 1:
            return record(Action.D)
        if t == r - 2:
            if n == 2 and last_coop == n - 1:
                return record(Action.C)
            return record(Action.D)
        if current_stock < 0.15 * cap:
            return record(Action.D)
        denom = max(n - 1, 1)
        f = last_coop / denom
        threshold = (n - 2) / denom
        if f >= threshold:
            return record(Action.C)
        if f < 0.5:
            if self.consec_defects >= 3 and current_stock >= 0.4 * cap and (r - t >= 4) and (t >= self.no_probe_until):
                self.probe_round = t
                return record(Action.C)
            return record(Action.D, rule5_defect=True)
        prev2 = int(history.opponent_cooperators[-2]) if t >= 2 else 0
        if current_stock >= 0.6 * cap and last_coop >= prev2:
            return record(Action.C)
        if self.consec_defects >= 3 and current_stock >= 0.4 * cap and (r - t >= 4) and (t >= self.no_probe_until):
            self.probe_round = t
            return record(Action.C)
        return record(Action.D, rule5_defect=True)

class Strategy_INDIVIDUALISTIC_5(BaseStrategy):
    """
    Sustainable Extraction with Punishment and Endgame Grab.
    Cooperate to preserve stock while opponents cooperate; punish
    multi-defector rounds, defect permanently in hostile pools,
    grab in the endgame or when stock collapses.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.avg_coop = 1.0

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        opp = max(n - 1, 1)
        coop_frac_last = None
        if t > 0:
            coop_frac_last = history.opponent_cooperators[-1] / opp
            self.avg_coop = 0.6 * coop_frac_last + 0.4 * self.avg_coop
        if t == r - 1:
            return Action.D
        if t == r - 2:
            if n >= 3 or self.avg_coop < 0.8:
                return Action.D
            return Action.C
        if current_stock < 0.1 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if self.avg_coop < 0.5:
            return Action.D
        defectors_last = opp * (1.0 - coop_frac_last)
        if defectors_last >= 2 and (not (defectors_last <= 1.5 and current_stock >= 0.5 * cap)):
            return Action.D
        return Action.C

class Strategy_INDIVIDUALISTIC_6(BaseStrategy):
    """
    Sustainable Exploiter: cooperate when opponents sustain the pool,
    free-ride occasionally, defect at endgame or when pool is dying.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description
        self.grudge = 0
        self.last_freeride = -10 ** 9
        self.freeride_allowed = game_description.n_players > 2

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        gd = self.game_description
        n, r, cap = (gd.n_players, gd.n_rounds, gd.capacity)
        t = history.round_number
        if r <= 3:
            return Action.D
        if t >= r - 2:
            return Action.D
        if current_stock < 0.1 * cap:
            return Action.D
        if t == 0:
            return Action.C
        opp = max(n - 1, 1)
        f = history.opponent_cooperators[-1] / opp
        if f < 0.5:
            self.grudge += 1
        elif f >= 0.75:
            self.grudge = 0
        if self.last_freeride == t - 1 and f < 1:
            self.freeride_allowed = False
        if self.freeride_allowed and f == 1 and (current_stock >= 0.9 * cap) and (t - self.last_freeride >= 3):
            self.last_freeride = t
            return Action.D
        if n == 2:
            if f == 1 and current_stock >= 0.3 * cap and (self.grudge <= 1):
                return Action.C
            return Action.D
        if current_stock >= 0.5 * cap and f >= 0.5:
            self.grudge = 0
        if f >= 0.5 and self.grudge <= 1 and (current_stock >= 0.3 * cap):
            return Action.C
        return Action.D

class Strategy_INDIVIDUALISTIC_7(BaseStrategy):
    """
    Sustainable Extractor with Endgame Grab: cooperate when opponents and
    stock health justify investment in future harvests; defect in endgame,
    on dead pools, or when opponents defect too much.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = self.game_description.capacity
        t = history.round_number
        k = r - t
        if k == 1 or (k == 2 and n <= 4):
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        if k <= 2:
            return Action.D
        n_opp = max(n - 1, 1)
        coop_frac = history.opponent_cooperators[-1] / n_opp
        if coop_frac >= 0.5 and current_stock >= 0.4 * cap:
            return Action.C
        if coop_frac >= (n - 1) / n:
            return Action.C
        return Action.D

class Strategy_INDIVIDUALISTIC_8(BaseStrategy):
    """
    Sustainable Extraction with Punishment and Endgame Harvest.
    Cooperates while opponents mostly cooperate, matches middling cooperation
    probabilistically, defects against majority defection, harvests at endgame.
    """

    def __init__(self, game_description: CommonPoolDescription):
        self.game_description = game_description

    def __call__(self, history: PlayerHistory, current_stock: float) -> Action:
        n = self.game_description.n_players
        r = self.game_description.n_rounds
        cap = float(self.game_description.capacity)
        t = history.round_number
        if t == r - 1:
            return Action.D
        if current_stock < 0.05 * cap:
            return Action.D
        if t == 0:
            return Action.C
        k = int(history.opponent_cooperators[-1])
        n_opp = max(n - 1, 1)
        if t == r - 2 and k < (n - 1) / 2.0:
            return Action.D
        if k >= n - 2:
            return Action.C
        if k >= math.ceil((n - 1) / 2):
            if current_stock < 0.5 * cap:
                return Action.C
            if random.random() < k / n_opp:
                return Action.C
            return Action.D
        return Action.D